// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wmkaqutyrgyckkpoexcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indta2FxdXR5cmd5Y2trcG9leGN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3NzY3ODUsImV4cCI6MjA2OTM1Mjc4NX0.IY3vScZfMzAgI8cdnMizN0NNQ47JzfJthbt9e26W9pI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});